version: '2'
services:
  web:
    build: .
    ports:
     - "8000:8000"
    volumes:
     - .:/app
    command: "python -u /app/manage.py runserver 0.0.0.0:8000"
    environment:
      DEBUG: 1
    links:
     - db
     - queue
    env_file:
      - debug.env

  celery:
    build: .
    links:
      - queue
      - maildev
      - db
    volumes:
     - .:/app
    command: "python -u -m celery -A djangodocker worker -l info"
    env_file:
      - debug.env

  db:
    image: "postgres:9.6"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: hunter2

  maildev:
    image: "djfarrelly/maildev:latest"
    command: >
      bin/maildev
      --web 80
      --smtp 25
      --incoming-user smtp@example.com
      --incoming-pass hunter2
    ports:
      - "1080:80"

  queue:
    image: "rabbitmq:3.7-management"
    hostname: "queue"
    ports:
      - "15672:15672"
