version: '2'
services:
  web:
    build: .
    ports:
     - "8000:8000"
    volumes:
     - .:/app
    links:
     - db
     - maildev
    environment:
      EMAIL_HOST: maildev
      EMAIL_PORT: 25
      URL: http://192.168.99.100:8000

  db:
    image: "postgres:9.6"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: hunter2

  maildev:
    image: "djfarrelly/maildev:latest"
    command: >
      bin/maildev
      --web 80
      --smtp 25
      --incoming-user smtp@example.com
      --incoming-pass hunter2
    ports:
      - "1080:80"
