version: '2'
services:
    web:
        build: .
        ports:
            - "8000:8000"
        volumes:
            - .:/app
        links:
            - db
        networks:
            stuxnet:
                ipv4_address: 1.3.3.7
    db:
        image: "postgres:9.6"
        ports:
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: hunter2
        networks:
            stuxnet: {}

networks:
  stuxnet:
      ipam:
        driver: default
        config:
            - subnet: 1.3.3.0/24
