version: '2'
services:
  web:
    image: "jmferrer/apache2-reverse-proxy:debian8"
    volumes:
      - ./apache:/etc/apache2/sites-enabled
    links:
      - app
    ports:
      - "80:80"

  app:
    build: .
    ports:
     - "8000:8000"
    volumes:
     - .:/app
    links:
     - db

  db:
    image: "postgres:9.6"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: hunter2